### ISSUE TITLE
Extension deletes all content in the file when auto-format is run.

### ISSUE THREAD

**Issue by himittal09** [LenAgain/vscode-latexindent#1]
The extension clears all content in the file when auto formatter is run via:

`Alt + Shift + F`.

**Comment by LenAgain** [comment]
Thanks for the issue. As you can probably tell this project hasn't received any development since I published it (although I have been using it), which is why I haven't gotten round to this issue.

If you're sill experiencing this issue could you please share the extension logs (in the output panel), as well as the file you're trying to format (before the content is wiped of course).
